export type AgentType = "ANTI_THEFT" | "AUTOMATED_CUSTOMER_SUPPORT" | "CHATBOT";

export enum AgentEnum {
  ANTI_THEFT = "ANTI_THEFT",
  AUTOMATED_CUSTOMER_SUPPORT = "AUTOMATED_CUSTOMER_SUPPORT",
  CHATBOT = "CHATBOT",
}
