export type AgentType = "ANTI_SCAM" | "AUTOMATED_CUSTOMER_SUPPORT" | "CHATBOT";

export enum AgentEnum {
  ANTI_SCAM = "ANTI_SCAM",
  AUTOMATED_CUSTOMER_SUPPORT = "AUTOMATED_CUSTOMER_SUPPORT",
  CHATBOT = "CHATBOT",
}
